package com.example.localization

import android.content.Context
import android.content.SharedPreferences
import androidx.compose.runtime.Composable
import androidx.compose.runtime.compositionLocalOf
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import java.util.Locale

enum class AppLanguage(
    val code: String,
    val displayName: String,
    val isRtl: Boolean
) {
    ARABIC("ar", "العربية", true),
    FRENCH("fr", "Français", false),
    ENGLISH("en", "English", false);

    companion object {
        fun fromCode(code: String): AppLanguage {
            return entries.find { it.code.equals(code, ignoreCase = true) } ?: ENGLISH
        }
    }
}

data class AppStrings(
    val appName: String,
    val tabMusic: String,
    val tabVideo: String,
    val tabUsb: String,
    val tabSettings: String,
    
    // Music Categorization / Playlists
    val allTracks: String,
    val artists: String,
    val albums: String,
    val folders: String,
    val tracksCount: String,
    val searchPlaceholder: String,
    val noTracksFound: String,
    val noVideosFound: String,
    val noUsbFound: String,
    val unknownArtist: String,
    val unknownAlbum: String,
    val selectArtistToView: String,
    val selectAlbumToView: String,
    val backToArtists: String,
    val backToAlbums: String,
    val backToFolders: String,
    val musicPlaylists: String,
    val backToMusicPlaylists: String,

    // Player
    val nowPlaying: String,
    val tapToFullscreen: String,
    val minimize: String,
    val fullscreen: String,
    val exitFullscreen: String,
    val play: String,
    val pause: String,
    val next: String,
    val previous: String,
    val selectMediaToPlay: String,
    val selectVideoToPlay: String,
    val videoPlayerHeader: String,
    val audioPlayerHeader: String,
    
    // USB & Storage
    val storageTitle: String,
    val storageScanButton: String,
    val scanningStorage: String,
    val storageMounted: String,
    val storageUnmounted: String,
    val storageRoot: String,
    val storageId: String,
    
    // Language & Car Settings
    val settingsTitle: String,
    val languageSection: String,
    val systemDefaultRuleNotice: String,
    val langArabic: String,
    val langFrench: String,
    val langEnglish: String,
    
    // Theme & Sensor & Dynamic Color
    val themeSection: String,
    val themeDark: String,
    val themeLight: String,
    val themeAutoSensor: String,
    val themeAutoTime: String,
    val themeAutoScreen: String,
    val lightSensorStatusAvailable: String,
    val lightSensorStatusUnavailable: String,
    val lightSensorAlternativeNotice: String,
    val dynamicColorTitle: String,
    val dynamicColorSubtitle: String,
    val compactScreenTitle: String,
    val compactScreenSubtitle: String,
    val compactScreenBadge: String,
    val keepScreenOnTitle: String,
    val keepScreenOnSubtitle: String,
    val keepScreenOnBadge: String,
    val fullscreenTitle: String,
    val fullscreenSubtitle: String,
    val fullscreenBadge: String,
    
    // Video Player Extra
    val videoSpeed: String,
    val videoAspect: String,
    val forward10: String,
    val replay10: String,

    // SWC
    val swcSimultaneousToast: String,
    val swcSimultaneousToggleToast: String,
    val swcSettingsSectionTitle: String,
    val swcSettingsSectionSubtitle: String,
    val swcPresetTitle: String,
    val swcPresetSmartAuto: String,
    val swcPresetDedicatedPause: String,
    val swcPresetSlowCanbus: String,
    val swcPresetPeugeot: String,
    val swcPresetCustom: String,
    val swcDualPressModeTitle: String,
    val swcDualPressModeSubtitle: String,
    val swcDualModeBoth: String,
    val swcDualModeStrictSimultaneous: String,
    val swcDualModeSequential: String,
    val swcDualModeDisabled: String,
    val swcDualPressWindowLabel: String,
    val swcDedicatedPauseTitle: String,
    val swcDedicatedPauseSubtitle: String,
    val swcLongPressModeTitle: String,
    val swcLongPressModeSubtitle: String,
    val swcLongPressModeContinuous: String,
    val swcLongPressModeStep: String,
    val swcLongPressModeFolder: String,
    val swcLongPressModeDisabled: String,
    val swcSeekStepLabel: String,
    val swcHoldThresholdLabel: String,
    val swcExtendedKeysTitle: String,
    val swcExtendedKeysSubtitle: String,
    val swcDebounceTitle: String,
    val swcDebounceSubtitle: String,
    val swcTesterTitle: String,
    val swcTesterSubtitle: String,
    val swcTesterWaiting: String,
    val swcTesterKeyDetected: String,
    val swcTesterAction: String,
    val swcTesterMappedFunction: String,
    val swcCustomizationTabTitle: String,
    val swcMapFunctionsTitle: String,
    val swcMapNextLabel: String,
    val swcMapPrevLabel: String,
    val swcMapPlayPauseLabel: String,
    val swcMapSelectHint: String,
    val swcMapWaiting: String,

    // Notifications & Extra controls
    val usbConnectedToast: String,
    val usbDisconnectedToast: String,
    val resumedPlayback: String,
    val fastForwarding: String,
    val rewinding: String,
    val internalStorage: String,

    // Video Playlists, Folders & Categorization
    val allVideos: String,
    val videoFolders: String,
    val videoPlaylists: String,
    val videoDrives: String,
    val backToVideoFolders: String,
    val backToVideoPlaylists: String,
    val backToVideoDrives: String,
    val playlistFavorites: String,
    val playlistShortClips: String,
    val playlistMovies: String,
    val playlistRecent: String,
    val searchVideosPlaceholder: String,
    val videoCountLabel: String,
    val addToFavorites: String,
    val removeFromFavorites: String,

    // Custom Playlists & Actions
    val createPlaylist: String,
    val playlistNamePlaceholder: String,
    val customPlaylists: String,
    val addToPlaylist: String,
    val removeFromPlaylist: String,
    val deleteMediaItem: String,
    val deleteMediaConfirmTitle: String,
    val deleteMediaConfirmMessage: String,
    val deletePlaylistConfirmTitle: String,
    val deletePlaylistConfirmMessage: String,
    val itemAddedToPlaylist: String,
    val itemRemovedFromPlaylist: String,
    val itemDeleted: String,
    val noCustomPlaylists: String,
    val trackActionTitle: String,
    val emptyPlaylist: String,
    val selectPlaylistToAdd: String,
    val newPlaylistTitle: String,
    val confirmDelete: String,
    val bulkDeleteConfirmMessage: String,
    val noPlaylistsFound: String,

    // Storage drives & USBs
    val storageDrives: String,
    val backToStorageDrives: String,
    val tabletInternalStorage: String,
    val sdCardStorage: String,
    val usbDriveLabel: String,
    val allStorageSources: String,

    // About App & Developer
    val aboutSectionTitle: String,
    val appDeveloperLabel: String,
    val developerName: String,
    val appVersionLabel: String,
    val appVersionValue: String,
    val appFeaturesSummary: String,

    // Auto open on USB insertion
    val autoOpenOnUsbTitle: String,
    val autoOpenOnUsbSubtitle: String,
    val autoOpenOnUsbBadge: String,

    // Fullscreen Visualizer Switch
    val visualizerModeCover: String,
    val visualizerModeBars: String,
    val toggleVisualizerTooltip: String,

    // Screen Scale & Font Size Settings
    val screenSizeTitle: String,
    val screenSizeSubtitle: String,
    val fontSizeTitle: String,
    val fontSizeSubtitle: String,

    // Custom SWC Profile & Buttons
    val swcCustomSectionTitle: String,
    val swcCustomSectionSubtitle: String,
    val swcCustomBtn1Label: String,
    val swcCustomBtn2Label: String,
    val swcCustomAccelLabel: String,
    val saveCustomProfileBtn: String,

    // Dashboard Widgets
    val widgetsSectionTitle: String,
    val widgetsSectionSubtitle: String,
    val showClock: String,
    val showDate: String,
    val showTemp: String,
    val showSpeed: String,
    val speedUnit: String,
    val tempUnit: String,

    // CAN-Bus Integration
    val canBusSectionTitle: String,
    val canBusSectionSubtitle: String,
    val canBusKeyRemapTitle: String,
    val canBusWheelSwitchTitle: String,
    val canBusWheelSwitchSubtitle: String,
    val canBusProtocolTitle: String,
    val canBusCarStatusTitle: String,
    val canBusVoltage: String,
    val canBusFuel: String,
    val canBusDoors: String,
    val canBusCleanUpSwc: String,
    val canBusSection: String,
    val carSpeedLabel: String,
    val carTempLabel: String,
    val canBusWheelModeLabel: String,
    val canBusWheelModeNormal: String,
    val canBusWheelModeReversed: String,
    val canBusWheelModeSmart: String,
    val canBusProtocolLabel: String,
    val canBusProtocolGeneric: String,
    val peugeotModeBadge: String,
    val peugeotModeHelp: String
)

val ArabicStrings = AppStrings(
    appName = "مشغل وسائط السيارة",
    tabMusic = "موسيقى",
    tabVideo = "فيديو",
    tabUsb = "USB التخزين",
    tabSettings = "الإعدادات",
    allTracks = "جميع المقاطع",
    artists = "المغنين",
    albums = "الألبومات",
    folders = "المجلدات",
    tracksCount = "مقطع",
    searchPlaceholder = "بحث بالاسم أو الفنان...",
    noTracksFound = "لم يتم العثور على مقاطع صوتية في الـ USB",
    noVideosFound = "لم يتم العثور على مقاطع فيديو في الـ USB",
    noUsbFound = "لم يتم العثور على وحدات USB متصلة. يرجى توصيل فلاش ديسك",
    unknownArtist = "فنان غير معروف",
    unknownAlbum = "ألبوم غير معروف",
    selectArtistToView = "اختر فناناً لعرض ألبوماته وأغانيه",
    selectAlbumToView = "اختر ألبوماً لعرض مقاطعه",
    backToArtists = "العودة لقائمة المغنين",
    backToAlbums = "العودة لقائمة الألبومات",
    backToFolders = "العودة للمجلدات",
    musicPlaylists = "قوائم التشغيل",
    backToMusicPlaylists = "العودة لقوائم التشغيل",
    nowPlaying = "قيد التشغيل الآن",
    tapToFullscreen = "انقر لملء الشاشة",
    minimize = "تصغير المشغل",
    fullscreen = "ملء الشاشة",
    exitFullscreen = "إنهاء ملء الشاشة",
    play = "تشغيل",
    pause = "إيقاف مؤقت",
    next = "التالي",
    previous = "السابق",
    selectMediaToPlay = "اختر مقطعاً للتشغيل في شاشة السيارة",
    selectVideoToPlay = "اختر فيديو لتشغيله في شاشة السيارة",
    videoPlayerHeader = "مشغل الفيديو الذكي",
    audioPlayerHeader = "مشغل الصوت الفائق",
    storageTitle = "وحدات التخزين (USB)",
    storageScanButton = "فحص التخزين",
    scanningStorage = "جاري الفحص التلقائي...",
    storageMounted = "متصل وجاهز",
    storageUnmounted = "غير متصل",
    storageRoot = "المسار",
    storageId = "المعرف",
    settingsTitle = "إعدادات السيارة واللغة",
    languageSection = "لغة التطبيق",
    systemDefaultRuleNotice = "اللغة الافتراضية تتبع لغة شاشة السيارة (عربي / فرنسي / إنجليزي تلقائياً، وإذا كانت لغة أخرى يتم فرض الإنجليزية)",
    langArabic = "العربية (Arabic)",
    langFrench = "الفرنسية (Français)",
    langEnglish = "الإنجليزية (English)",
    themeSection = "مظهر التطبيق والسمات",
    themeDark = "الوضع الليلي (داكن)",
    themeLight = "الوضع النهاري (فاتح)",
    themeAutoSensor = "تلقائي بحساس السيارة",
    themeAutoTime = "تلقائي حسب توقيت الساعة (شروق وغروب)",
    themeAutoScreen = "تلقائي حسب سطوع الشاشة والمصابيح",
    lightSensorStatusAvailable = "حساس إضاءة السيارة متاح: يتكيف تلقائياً بين الليل والنهار",
    lightSensorStatusUnavailable = "حساس الإضاءة غير مدعوم في جهاز سيارتك: يمكنك الاعتماد على خياري الساعة أو سطوع الشاشة",
    lightSensorAlternativeNotice = "بدائل ذكية للمركبات بدون مستشعر: التبديل التلقائي حسب توقيت الساعة أو حسب سطوع الشاشة ومصابيح السيارة!",
    dynamicColorTitle = "تلوين ديناميكي حسب غلاف الأغنية",
    dynamicColorSubtitle = "تغيير لمسات وأزرار التطبيق تلقائياً مع كل أغنية",
    compactScreenTitle = "احترام الشاشات الصغيرة",
    compactScreenSubtitle = "تحسين وضبط الأحجام والأزرار لشاشات السيارات المدمجة (7 بوصة وأقل)",
    compactScreenBadge = "وضع الشاشات المدمجة",
    keepScreenOnTitle = "إبقاء الشاشة قيد التشغيل دائماً",
    keepScreenOnSubtitle = "منع انطفاء أو قفل شاشة السيارة تلقائياً طالما أن التطبيق مفتوح",
    keepScreenOnBadge = "الشاشة تعمل دوماً",
    fullscreenTitle = "ملء الشاشة بالكامل (Fullscreen)",
    fullscreenSubtitle = "إخفاء أشرطة النظام بالكامل واستغلال شاشة السيارة بنسبة 100%",
    fullscreenBadge = "ملء الشاشة نشط",
    videoSpeed = "السرعة",
    videoAspect = "الأبعاد",
    forward10 = "+10 ث",
    replay10 = "-10 ث",
    swcSimultaneousToast = "تم الكشف عن الضغط المتزامن لأزرار المقود: إيقاف مؤقت",
    swcSimultaneousToggleToast = "أزرار المقود: تشغيل / إيقاف مؤقت",
    swcSettingsSectionTitle = "أزرار عجلة القيادة (SWC)",
    swcSettingsSectionSubtitle = "تخصيص استجابة أزرار المقود حسب نوع سيارتك وشاشتك لاختيار التوافق المثالي",
    swcPresetTitle = "الوضع المسبق للسيارة",
    swcPresetSmartAuto = "ذكي تلقائي (موصى به)",
    swcPresetDedicatedPause = "سيارة بزر Pause مستقل",
    swcPresetSlowCanbus = "كانباص بطيء / أزرار مقاومة",
    swcPresetPeugeot = "بيجو 207 / PSA (ذراع المقود)",
    swcPresetCustom = "تخصيص يدوي",
    swcDualPressModeTitle = "سلوك الضغط على زري التبديل (التالي + السابق)",
    swcDualPressModeSubtitle = "اختر كيفية استقبال الشاشة للضغط على الزرين لتفعيل التشغيل / الإيقاف المؤقت",
    swcDualModeBoth = "متزامن ومتتابع معاً (الذكي)",
    swcDualModeStrictSimultaneous = "متزامن فقط (في نفس اللحظة)",
    swcDualModeSequential = "متتابع فقط (الأول ثم الثاني)",
    swcDualModeDisabled = "معطل (اعتماد أزرار منفصلة)",
    swcDualPressWindowLabel = "نافذة زمن التقاط الزرين",
    swcDedicatedPauseTitle = "السيارة تملك زر تشغيل/إيقاف مستقل (Pause/Mute)",
    swcDedicatedPauseSubtitle = "إذا كانت سيارتك مزودة بزر تشغيل وإيقاف أو كتم، يمكنك تعطيل كومبو الزرين لتفادي الإيقاف بالخطأ",
    swcLongPressModeTitle = "وظيفة الضغط المطول على زري التبديل",
    swcLongPressModeSubtitle = "حدد ما يحدث عند الاستمرار بالضغط على زر التالي أو السابق",
    swcLongPressModeContinuous = "تسريع وإرجاع مستمر (تقديم >> / إرجاع <<)",
    swcLongPressModeStep = "قفزة زمنية واحدة (Seek Step)",
    swcLongPressModeFolder = "تخطي المجلد / الألبوم بالكامل",
    swcLongPressModeDisabled = "معطل (تبديل مقطع فقط)",
    swcSeekStepLabel = "مقدار القفزة بالثواني",
    swcHoldThresholdLabel = "مدة تفعيل الضغط المطول",
    swcExtendedKeysTitle = "دعم الأكواد الموسعة للشاشات الصينية و CAN-Bus",
    swcExtendedKeysSubtitle = "التعرف على أزرار القنوات والأسهم (Channel Up/Down, D-Pad) كأزرار تبديل",
    swcDebounceTitle = "مانع تكرار الإشارات المزدوجة (Debounce)",
    swcDebounceSubtitle = "تجاهل النبضات السريعة المكررة التي ترسلها بعض وحدات CAN-bus لمنع تخطي أغنيتين",
    swcTesterTitle = "لوحة الفحص المباشر لأزرار المقود",
    swcTesterSubtitle = "اضغط على أي زر على عجلة القيادة الآن لرؤية الكود المستلم وكيف يفسره التطبيق فوراً",
    swcTesterWaiting = "بانتظار الضغط على أي زر من المقود...",
    swcTesterKeyDetected = "الزر الملتقط",
    swcTesterAction = "نوع الحدث",
    swcTesterMappedFunction = "الوظيفة المنفذة",
    swcCustomizationTabTitle = "كوستوميشن (Customization)",
    swcMapFunctionsTitle = "تعيين وظائف الأزرار",
    swcMapNextLabel = "زر التالي (Next)",
    swcMapPrevLabel = "زر السابق (Prev)",
    swcMapPlayPauseLabel = "زر التشغيل/الإيقاف",
    swcMapSelectHint = "اضغط على الزر المراد في المقود لتعيينه",
    swcMapWaiting = "بانتظار الضغط...",
    usbConnectedToast = "تم توصيل وحدة تخزين USB: %s",
    usbDisconnectedToast = "تم فصل وحدة تخزين USB: %s",
    resumedPlayback = "تم استئناف التشغيل من آخر نقطة توقف",
    fastForwarding = "تقديم سريع >>",
    rewinding = "<< إرجاع سريع",
    internalStorage = "ذاكرة الجهاز الداخلية",
    allVideos = "جميع الفيديوهات",
    videoFolders = "المجلدات",
    videoPlaylists = "قوائم التشغيل",
    videoDrives = "وسائط التخزين",
    backToVideoFolders = "العودة لمجلدات الفيديو",
    backToVideoPlaylists = "العودة لقوائم التشغيل",
    backToVideoDrives = "العودة لوحدات التخزين",
    playlistFavorites = "المفضلة ⭐",
    playlistShortClips = "مقاطع قصيرة (< 5 د)",
    playlistMovies = "أفلام ومسلسلات (> 10 د)",
    playlistRecent = "أحدث الفيديوهات",
    searchVideosPlaceholder = "بحث في الفيديوهات أو المجلد...",
    videoCountLabel = "%d فيديو",
    addToFavorites = "إضافة للمفضلة",
    removeFromFavorites = "إزالة من المفضلة",
    createPlaylist = "إنشاء قائمة تشغيل جديدة",
    playlistNamePlaceholder = "اكتب اسم قائمة التشغيل...",
    customPlaylists = "قوائم التشغيل الخاصة بي",
    addToPlaylist = "إضافة إلى قائمة تشغيل",
    removeFromPlaylist = "إزالة من قائمة التشغيل",
    deleteMediaItem = "حذف الملف",
    deleteMediaConfirmTitle = "تأكيد حذف الملف",
    deleteMediaConfirmMessage = "هل أنت متأكد من رغبتك في حذف هذا الملف نهائياً؟",
    deletePlaylistConfirmTitle = "حذف قائمة التشغيل",
    deletePlaylistConfirmMessage = "هل أنت متأكد من حذف قائمة التشغيل هذه؟",
    itemAddedToPlaylist = "تمت الإضافة إلى قائمة التشغيل بنجاح",
    itemRemovedFromPlaylist = "تمت إزالة الملف من قائمة التشغيل",
    itemDeleted = "تم حذف الملف بنجاح",
    noCustomPlaylists = "لا توجد قوائم تشغيل مخصصة، انقر على زر الإنشاء لإنشاء أول قائمة!",
    trackActionTitle = "خيارات الوسائط",
    emptyPlaylist = "هذه القائمة فارغة حالياً",
    selectPlaylistToAdd = "اختر قائمة التشغيل",
    newPlaylistTitle = "قائمة جديدة",
    confirmDelete = "تأكيد الحذف",
    bulkDeleteConfirmMessage = "هل أنت متأكد من حذف العناصر المختارة؟",
    noPlaylistsFound = "لم يتم العثور على قوائم تشغيل",
    storageDrives = "وسائط التخزين",
    backToStorageDrives = "العودة لوسائط التخزين",
    tabletInternalStorage = "ذاكرة التابلت الداخلية",
    sdCardStorage = "بطاقة ذاكرة SD",
    usbDriveLabel = "فلاش USB",
    allStorageSources = "جميع الوسائط",
    aboutSectionTitle = "حول التطبيق والمعلومات",
    appDeveloperLabel = "المطور",
    developerName = "achour tech pro",
    appVersionLabel = "الإصدار",
    appVersionValue = "v2.5 (Car Head Unit Edition)",
    appFeaturesSummary = "مشغل وسائط متطور مصمم خصيصاً لشاشات سيارات أندرويد مع أزرار لمس كبيرة ودعم الفلاشات ومفاتيح المقود ومؤثرات صوتية بصرية.",
    autoOpenOnUsbTitle = "فتح التطبيق تلقائياً عند إدخال USB",
    autoOpenOnUsbSubtitle = "تشغيل التطبيق مباشرة على شاشة السيارة بمجرد توصيل فلاش ميموري أو كارت ميموري",
    autoOpenOnUsbBadge = "فتح تلقائي",
    visualizerModeCover = "غلاف الأغنية",
    visualizerModeBars = "مؤثرات الصوت (الأعمدة)",
    toggleVisualizerTooltip = "التبديل بين الغلاف وأعمدة الصوت",
    screenSizeTitle = "حجم الشاشة وعرض الواجهة (Screen Scale)",
    screenSizeSubtitle = "ضبط حجم ومقياس عناصر واجهة مشغل السيارة لتناسب الشاشة بدقة",
    fontSizeTitle = "حجم الخط (Font Size Scale)",
    fontSizeSubtitle = "تكبير أو تصغير حجم النصوص في جميع قوائم وشاشات التطبيق",
    swcCustomSectionTitle = "تخصيص أزرار المقود (Customization)",
    swcCustomSectionSubtitle = "إعداد أزرار المقود حسب رغبتك وسرعة التسريع المطول",
    swcCustomBtn1Label = "كود زر التالي (Next)",
    swcCustomBtn2Label = "كود زر السابق (Previous)",
    swcCustomAccelLabel = "سرعة التقديم/الإرجاع المطول",
    saveCustomProfileBtn = "حفظ التخصيص كإعداد نهائي مخصص",

    // Dashboard Widgets
    widgetsSectionTitle = "إضافات لوحة القيادة",
    widgetsSectionSubtitle = "تكوين المعلومات المعروضة في وضع الشاشة الكاملة",
    showClock = "عرض الساعة",
    showDate = "عرض التاريخ",
    showTemp = "عرض درجة الحرارة",
    showSpeed = "عرض سرعة السيارة",
    speedUnit = "كم/س",
    tempUnit = "°م",
    canBusSectionTitle = "تكامل نظام CAN-Bus",
    canBusSectionSubtitle = "إعدادات متقدمة للاتصال المباشر بنظام السيارة الإلكتروني",
    canBusKeyRemapTitle = "إعادة تعيين أزرار CAN-Bus",
    canBusWheelSwitchTitle = "تبديل وضع عجلة المقود",
    canBusWheelSwitchSubtitle = "تغيير كيفية تفسير إشارات التدوير من نظام الكان باص",
    canBusProtocolTitle = "بروتوكول السيارة (CAN Protocol)",
    canBusCarStatusTitle = "حالة السيارة (Car Info)",
    canBusVoltage = "جهد البطارية",
    canBusFuel = "مستوى الوقود",
    canBusDoors = "حالة الأبواب",
    canBusCleanUpSwc = "تنظيف الإعدادات غير النشطة",
    canBusSection = "إعدادات CAN-Bus",
    carSpeedLabel = "سرعة السيارة",
    carTempLabel = "حرارة الجو",
    canBusWheelModeLabel = "وضع عجلة المقود",
    canBusWheelModeNormal = "عادي",
    canBusWheelModeReversed = "معكوس",
    canBusWheelModeSmart = "ذكي",
    canBusProtocolLabel = "بروتوكول CAN",
    canBusProtocolGeneric = "عام (أندرويد)",
    peugeotModeBadge = "وضع مخصص لسيارة بيجو 207 (PSA)",
    peugeotModeHelp = "تفعيل الدعم المباشر لعجلة ذراع المقود (Rotary Stalk) وأزرار الصوت وزر Source"
)

val EnglishStrings = AppStrings(
    appName = "Car Media Player",
    tabMusic = "Music",
    tabVideo = "Video",
    tabUsb = "USB Storage",
    tabSettings = "Settings",
    allTracks = "All Tracks",
    artists = "Artists",
    albums = "Albums",
    folders = "Folders",
    tracksCount = "tracks",
    searchPlaceholder = "Search by title or artist...",
    noTracksFound = "No music tracks found on USB",
    noVideosFound = "No videos found on USB",
    noUsbFound = "No connected USB drives found. Please insert a USB drive",
    unknownArtist = "Unknown Artist",
    unknownAlbum = "Unknown Album",
    selectArtistToView = "Select an artist to view their songs",
    selectAlbumToView = "Select an album to view its tracks",
    backToArtists = "Back to Artists",
    backToAlbums = "Back to Albums",
    backToFolders = "Back to Folders",
    musicPlaylists = "Playlists",
    backToMusicPlaylists = "Back to Playlists",
    nowPlaying = "Now Playing",
    tapToFullscreen = "Tap for Fullscreen",
    minimize = "Minimize Player",
    fullscreen = "Fullscreen",
    exitFullscreen = "Exit Fullscreen",
    play = "Play",
    pause = "Pause",
    next = "Next",
    previous = "Previous",
    selectMediaToPlay = "Select a track to play on car display",
    selectVideoToPlay = "Select a video to play on car display",
    videoPlayerHeader = "Smart Video Player",
    audioPlayerHeader = "Car Audio Player",
    storageTitle = "USB Storage Devices",
    storageScanButton = "Scan Devices",
    scanningStorage = "Scanning USB media...",
    storageMounted = "Mounted & Ready",
    storageUnmounted = "Unmounted",
    storageRoot = "Path",
    storageId = "ID",
    settingsTitle = "Car & Language Settings",
    languageSection = "App Language",
    systemDefaultRuleNotice = "Defaults to car system language (Arabic / French / English, and strictly English for any other language)",
    langArabic = "Arabic (العربية)",
    langFrench = "French (Français)",
    langEnglish = "English (English)",
    themeSection = "App Theme & Appearance",
    themeDark = "Night Mode (Dark)",
    themeLight = "Day Mode (Light)",
    themeAutoSensor = "Auto (Car Light Sensor)",
    themeAutoTime = "Auto by Time (Sunrise/Sunset)",
    themeAutoScreen = "Auto by Screen Brightness & Lights",
    lightSensorStatusAvailable = "Car light sensor active: auto-switches day & night",
    lightSensorStatusUnavailable = "Light sensor not detected: smart alternatives (time / screen brightness) active",
    lightSensorAlternativeNotice = "Smart alternatives for vehicles without sensor: Auto-switch by Time or by Screen Brightness & Headlights!",
    dynamicColorTitle = "Dynamic Colors from Album Art",
    dynamicColorSubtitle = "Adapts accent styling to the currently playing song",
    compactScreenTitle = "Compact Screen Mode",
    compactScreenSubtitle = "Optimize layouts, margins, and controls for small car displays (≤ 7 inches)",
    compactScreenBadge = "Compact Display Mode",
    keepScreenOnTitle = "Keep Screen On Always",
    keepScreenOnSubtitle = "Prevent the car display from sleeping or dimming while the app is open",
    keepScreenOnBadge = "Screen Always On",
    fullscreenTitle = "Immersive Fullscreen",
    fullscreenSubtitle = "Hide system navigation and status bars to use 100% of the car display",
    fullscreenBadge = "Fullscreen Active",
    videoSpeed = "Speed",
    videoAspect = "Aspect",
    forward10 = "+10s",
    replay10 = "-10s",
    swcSimultaneousToast = "Steering wheel simultaneous press detected: Paused",
    swcSimultaneousToggleToast = "Steering wheel simultaneous press: Play / Pause toggle",
    swcSettingsSectionTitle = "Steering Wheel Controls (SWC)",
    swcSettingsSectionSubtitle = "Customize button behaviors, timing windows, and seek speeds for your specific vehicle",
    swcPresetTitle = "Vehicle Preset Profile",
    swcPresetSmartAuto = "Smart Auto (Recommended)",
    swcPresetDedicatedPause = "Dedicated Pause Button",
    swcPresetSlowCanbus = "Slow CAN-Bus / Resistive Keys",
    swcPresetPeugeot = "Peugeot 207 / PSA (Stalk Control)",
    swcPresetCustom = "Custom Profile",
    swcDualPressModeTitle = "Track Skip Dual-Button Behavior (Next + Prev)",
    swcDualPressModeSubtitle = "Choose how dual key detection triggers Play / Pause toggle",
    swcDualModeBoth = "Simultaneous & Sequential (Smart)",
    swcDualModeStrictSimultaneous = "Simultaneous Only (Exact same time)",
    swcDualModeSequential = "Sequential Only (First then Second)",
    swcDualModeDisabled = "Disabled (Use dedicated button)",
    swcDualPressWindowLabel = "Dual Press Detection Window",
    swcDedicatedPauseTitle = "Vehicle has Dedicated Play/Pause/Mute Button",
    swcDedicatedPauseSubtitle = "If your steering wheel has a Play/Pause button, you can disable the dual-button combo to avoid accidental pauses",
    swcLongPressModeTitle = "Long-Press Function on Next / Previous",
    swcLongPressModeSubtitle = "Define what happens when holding down the Next or Previous button",
    swcLongPressModeContinuous = "Continuous Seeking (Fast-Forward >> / Rewind <<)",
    swcLongPressModeStep = "Single Jump Step (e.g. +10s / -10s)",
    swcLongPressModeFolder = "Skip Whole Folder / Album",
    swcLongPressModeDisabled = "Disabled (Single track skip only)",
    swcSeekStepLabel = "Seek Step Duration",
    swcHoldThresholdLabel = "Long-Press Hold Threshold",
    swcExtendedKeysTitle = "Accept Extended Keys (CAN-Bus & Head Units)",
    swcExtendedKeysSubtitle = "Recognize Channel Up/Down and D-Pad navigation codes as Next/Prev keys",
    swcDebounceTitle = "Anti-Double-Click Filter (Debounce)",
    swcDebounceSubtitle = "Suppresses rapid duplicate CAN-bus pulses to avoid skipping two tracks at once",
    swcTesterTitle = "Live Steering Wheel Key Monitor",
    swcTesterSubtitle = "Press any steering wheel button now to see the exact code received and how the app interprets it",
    swcTesterWaiting = "Waiting for steering wheel key press...",
    swcTesterKeyDetected = "Detected Key",
    swcTesterAction = "Event Action",
    swcTesterMappedFunction = "Mapped Action",
    swcCustomizationTabTitle = "Customization",
    swcMapFunctionsTitle = "Map Button Functions",
    swcMapNextLabel = "Next Button",
    swcMapPrevLabel = "Prev Button",
    swcMapPlayPauseLabel = "Play/Pause Button",
    swcMapSelectHint = "Press steering button to map",
    swcMapWaiting = "Waiting for press...",
    usbConnectedToast = "USB Storage Connected: %s",
    usbDisconnectedToast = "USB Storage Removed: %s",
    resumedPlayback = "Resuming playback from where you left off",
    fastForwarding = "Fast Forwarding >>",
    rewinding = "<< Rewinding",
    internalStorage = "Internal Storage",
    allVideos = "All Videos",
    videoFolders = "Folders",
    videoPlaylists = "Playlists",
    videoDrives = "Drives",
    backToVideoFolders = "Back to Folders",
    backToVideoPlaylists = "Back to Playlists",
    backToVideoDrives = "Back to Drives",
    playlistFavorites = "Favorites ⭐",
    playlistShortClips = "Short Clips (< 5m)",
    playlistMovies = "Movies & Episodes (> 10m)",
    playlistRecent = "Recently Added",
    searchVideosPlaceholder = "Search videos or folder...",
    videoCountLabel = "%d videos",
    addToFavorites = "Add to Favorites",
    removeFromFavorites = "Remove from Favorites",
    createPlaylist = "Create New Playlist",
    playlistNamePlaceholder = "Enter playlist name...",
    customPlaylists = "My Playlists",
    addToPlaylist = "Add to Playlist",
    removeFromPlaylist = "Remove from Playlist",
    deleteMediaItem = "Delete File",
    deleteMediaConfirmTitle = "Confirm Deletion",
    deleteMediaConfirmMessage = "Are you sure you want to permanently delete this file?",
    deletePlaylistConfirmTitle = "Delete Playlist",
    deletePlaylistConfirmMessage = "Are you sure you want to delete this playlist?",
    itemAddedToPlaylist = "Added to playlist successfully",
    itemRemovedFromPlaylist = "Removed from playlist",
    itemDeleted = "File deleted successfully",
    noCustomPlaylists = "No custom playlists yet. Tap Create to make your first playlist!",
    trackActionTitle = "Media Options",
    emptyPlaylist = "This playlist is currently empty",
    selectPlaylistToAdd = "Select Playlist",
    newPlaylistTitle = "New Playlist",
    confirmDelete = "Confirm Delete",
    bulkDeleteConfirmMessage = "Are you sure you want to delete the selected items?",
    noPlaylistsFound = "No playlists found",
    storageDrives = "Storage & USB",
    backToStorageDrives = "Back to Storage Drives",
    tabletInternalStorage = "Tablet Internal Storage",
    sdCardStorage = "SD Card Storage",
    usbDriveLabel = "USB Drive",
    allStorageSources = "All Storage Sources",
    aboutSectionTitle = "About App & System",
    appDeveloperLabel = "Developer",
    developerName = "achour tech pro",
    appVersionLabel = "Version",
    appVersionValue = "v2.5 (Car Head Unit Edition)",
    appFeaturesSummary = "Automotive-tailored media player designed for car Android head units with massive controls, USB OTG detection, steering wheel controls, and live audio visualizers.",
    autoOpenOnUsbTitle = "Auto-launch on USB Insertion",
    autoOpenOnUsbSubtitle = "Automatically bring Car Media Player to the screen when a USB drive is connected",
    autoOpenOnUsbBadge = "Auto Launch",
    visualizerModeCover = "Album Cover",
    visualizerModeBars = "Audio Visualizer Bars",
    toggleVisualizerTooltip = "Toggle between Album Art and Dynamic Equalizer Bars",
    screenSizeTitle = "Screen Size & UI Scale",
    screenSizeSubtitle = "Adjust UI element dimensions and scaling to fit your car screen perfectly",
    fontSizeTitle = "Font Size Scale",
    fontSizeSubtitle = "Scale up or down text sizes across all lists and player screens",
    swcCustomSectionTitle = "Custom SWC Button Profile",
    swcCustomSectionSubtitle = "Configure dual-button pause combo (stop/brake), long-press acceleration, and save as final custom settings",
    swcCustomBtn1Label = "Steering Button 1 Key Code",
    swcCustomBtn2Label = "Steering Button 2 Key Code",
    swcCustomAccelLabel = "Long-Press Acceleration Speed Factor",
    saveCustomProfileBtn = "Save as Final Custom Setting",

    // Dashboard Widgets
    widgetsSectionTitle = "Dashboard Widgets",
    widgetsSectionSubtitle = "Configure information displayed in fullscreen mode",
    showClock = "Show Clock",
    showDate = "Show Date",
    showTemp = "Show Temperature",
    showSpeed = "Show Car Speed",
    speedUnit = "km/h",
    tempUnit = "°C",
    canBusSectionTitle = "CAN-Bus Integration",
    canBusSectionSubtitle = "Advanced settings for direct vehicle system communication",
    canBusKeyRemapTitle = "CAN-Bus Key Remapping",
    canBusWheelSwitchTitle = "Wheel Mode Switch",
    canBusWheelSwitchSubtitle = "Change how CAN-Bus rotary/wheel signals are interpreted",
    canBusProtocolTitle = "CAN Protocol",
    canBusCarStatusTitle = "Car Info",
    canBusVoltage = "Battery Voltage",
    canBusFuel = "Fuel Level",
    canBusDoors = "Door Status",
    canBusCleanUpSwc = "Clean Up Inactive Settings",
    canBusSection = "CAN-Bus Settings",
    carSpeedLabel = "Car Speed",
    carTempLabel = "Ambient Temp",
    canBusWheelModeLabel = "Steering Wheel Mode",
    canBusWheelModeNormal = "Normal",
    canBusWheelModeReversed = "Reversed",
    canBusWheelModeSmart = "Smart",
    canBusProtocolLabel = "CAN Protocol",
    canBusProtocolGeneric = "Generic (Android)",
    peugeotModeBadge = "Peugeot 207 / PSA Dedicated Mode",
    peugeotModeHelp = "Optimized for Peugeot 207 rotary stalk wheel, Source key, and Raise/SimpleSoft CAN boxes"
)

val FrenchStrings = AppStrings(
    appName = "Lecteur Média Voiture",
    tabMusic = "Musique",
    tabVideo = "Vidéo",
    tabUsb = "Stockage USB",
    tabSettings = "Paramètres",
    allTracks = "Tous les titres",
    artists = "Artistes",
    albums = "Albums",
    folders = "Dossiers",
    tracksCount = "pistes",
    searchPlaceholder = "Rechercher par titre ou artiste...",
    noTracksFound = "Aucune piste musicale trouvée sur la clé USB",
    noVideosFound = "Aucune vidéo trouvée sur la clé USB",
    noUsbFound = "Aucun support USB détecté. Veuillez brancher une clé USB",
    unknownArtist = "Artiste Inconnu",
    unknownAlbum = "Album Inconnu",
    selectArtistToView = "Sélectionnez un artiste pour afficher ses titres",
    selectAlbumToView = "Sélectionnez un album pour afficher ses pistes",
    backToArtists = "Retour aux artistes",
    backToAlbums = "Retour aux albums",
    backToFolders = "Retour aux dossiers",
    musicPlaylists = "Listes de lecture",
    backToMusicPlaylists = "Retour aux listes",
    nowPlaying = "Lecture en cours",
    tapToFullscreen = "Appuyez pour plein écran",
    minimize = "Réduire le lecteur",
    fullscreen = "Plein écran",
    exitFullscreen = "Quitter plein écran",
    play = "Lecture",
    pause = "Pause",
    next = "Suivant",
    previous = "Précédent",
    selectMediaToPlay = "Sélectionnez un titre à lire sur l'écran du véhicule",
    selectVideoToPlay = "Sélectionnez une vidéo à lire sur l'écran du véhicule",
    videoPlayerHeader = "Lecteur Vidéo Intelligent",
    audioPlayerHeader = "Lecteur Audio Voiture",
    storageTitle = "Stockage USB",
    storageScanButton = "Analyser",
    scanningStorage = "Analyse des médias USB en cours...",
    storageMounted = "Monté et prêt",
    storageUnmounted = "Non monté",
    storageRoot = "Chemin",
    storageId = "Identifiant",
    settingsTitle = "Paramètres du véhicule et langue",
    languageSection = "Langue de l'application",
    systemDefaultRuleNotice = "Par défaut selon la langue du véhicule (Arabe / Français / Anglais, et strictement Anglais pour toute autre langue)",
    langArabic = "Arabe (العربية)",
    langFrench = "Français (Français)",
    langEnglish = "Anglais (English)",
    themeSection = "Thème de l'application",
    themeDark = "Mode Nuit (Sombre)",
    themeLight = "Mode Jour (Clair)",
    themeAutoSensor = "Auto (Capteur de lumière)",
    themeAutoTime = "Auto selon l'heure (Lever/Coucher)",
    themeAutoScreen = "Auto selon luminosité de l'écran",
    lightSensorStatusAvailable = "Capteur de luminosité actif : bascule auto jour/nuit",
    lightSensorStatusUnavailable = "Capteur non détecté : alternatives intelligentes (heure / luminosité) actives",
    lightSensorAlternativeNotice = "Alternatives pour véhicules sans capteur : bascule selon l'heure ou la luminosité de l'écran !",
    dynamicColorTitle = "Couleurs dynamiques selon la pochette",
    dynamicColorSubtitle = "Adapte les accents et touches selon la chanson en cours",
    compactScreenTitle = "Mode Petits Écrans",
    compactScreenSubtitle = "Optimiser les marges et les boutons pour petits écrans de voiture (≤ 7 pouces)",
    compactScreenBadge = "Mode Écran Compact",
    keepScreenOnTitle = "Garder l'écran allumé",
    keepScreenOnSubtitle = "Empêcher la mise en veille de l'écran pendant que l'application est ouverte",
    keepScreenOnBadge = "Écran toujours actif",
    fullscreenTitle = "Plein écran immersif",
    fullscreenSubtitle = "Masquer les barres système pour occuper 100% de l'écran de la voiture",
    fullscreenBadge = "Plein Écran Actif",
    videoSpeed = "Vitesse",
    videoAspect = "Format",
    forward10 = "+10s",
    replay10 = "-10s",
    swcSimultaneousToast = "Commandes au volant : touches simultanées détectées (Pause)",
    swcSimultaneousToggleToast = "Commandes au volant : touches simultanées (Lecture / Pause)",
    swcSettingsSectionTitle = "Commandes au Volant (SWC)",
    swcSettingsSectionSubtitle = "Personnalisez le comportement des touches et la vitesse de défilement selon votre véhicule",
    swcPresetTitle = "Profil prédéfini du véhicule",
    swcPresetSmartAuto = "Auto Intelligent (Recommandé)",
    swcPresetDedicatedPause = "Bouton Pause Dédié",
    swcPresetSlowCanbus = "CAN-Bus Lent / Résistif",
    swcPresetPeugeot = "Peugeot 207 / PSA (Commodo)",
    swcPresetCustom = "Personnalisé",
    swcDualPressModeTitle = "Comportement double touche (Suivant + Précédent)",
    swcDualPressModeSubtitle = "Choisissez comment la double pression active la Lecture / Pause",
    swcDualModeBoth = "Simultané et Séquentiel (Intelligent)",
    swcDualModeStrictSimultaneous = "Simultané uniquement (Même instant)",
    swcDualModeSequential = "Séquentiel uniquement (L'un après l'autre)",
    swcDualModeDisabled = "Désactivé (Boutons dédiés uniquement)",
    swcDualPressWindowLabel = "Fenêtre de détection de la combinaison",
    swcDedicatedPauseTitle = "Le véhicule a un bouton Lecture/Pause/Muet dédié",
    swcDedicatedPauseSubtitle = "Si votre volant dispose d'un bouton Pause, désactivez la combinaison double pour éviter les pauses accidentelles",
    swcLongPressModeTitle = "Action de pression longue sur Suivant / Précédent",
    swcLongPressModeSubtitle = "Définissez ce qui se produit en maintenant la touche enfoncée",
    swcLongPressModeContinuous = "Avance / Retour rapide continu (>> / <<)",
    swcLongPressModeStep = "Saut temporel unique (ex: +10s / -10s)",
    swcLongPressModeFolder = "Passer au dossier / album entier",
    swcLongPressModeDisabled = "Désactivé (Piste suivante uniquement)",
    swcSeekStepLabel = "Durée du saut en secondes",
    swcHoldThresholdLabel = "Délai d'appui long requis",
    swcExtendedKeysTitle = "Accepter touches étendues (CAN-Bus / Écrans Android)",
    swcExtendedKeysSubtitle = "Reconnaître Channel Up/Down et flèches D-Pad comme touches Suivant/Précédent",
    swcDebounceTitle = "Filtre anti-rebond (Debounce)",
    swcDebounceSubtitle = "Ignore les impulsions doubles rapides pour éviter de sauter 2 pistes d'un coup",
    swcTesterTitle = "Moniteur de test des touches au volant",
    swcTesterSubtitle = "Appuyez sur un bouton de votre volant pour vérifier le code reçu et l'action associée",
    swcTesterWaiting = "En attente d'une touche au volant...",
    swcTesterKeyDetected = "Touche détectée",
    swcTesterAction = "Action",
    swcTesterMappedFunction = "Fonction mappée",
    swcCustomizationTabTitle = "Customisation",
    swcMapFunctionsTitle = "Mapper les fonctions",
    swcMapNextLabel = "Bouton Suivant",
    swcMapPrevLabel = "Bouton Précédent",
    swcMapPlayPauseLabel = "Bouton Lecture/Pause",
    swcMapSelectHint = "Appuyez sur le bouton pour mapper",
    swcMapWaiting = "En attente d'appui...",
    usbConnectedToast = "Clé USB connectée : %s",
    usbDisconnectedToast = "Clé USB retirée : %s",
    resumedPlayback = "Reprise de la lecture là où vous vous étiez arrêté",
    fastForwarding = "Avance rapide >>",
    rewinding = "<< Retour rapide",
    internalStorage = "Stockage interne",
    allVideos = "Toutes les vidéos",
    videoFolders = "Dossiers",
    videoPlaylists = "Listes de lecture",
    videoDrives = "Supports",
    backToVideoFolders = "Retour aux dossiers",
    backToVideoPlaylists = "Retour aux listes",
    backToVideoDrives = "Retour aux supports",
    playlistFavorites = "Favoris ⭐",
    playlistShortClips = "Courts métrages (< 5m)",
    playlistMovies = "Films & Épisodes (> 10m)",
    playlistRecent = "Récemment ajoutées",
    searchVideosPlaceholder = "Rechercher des vidéos ou dossiers...",
    videoCountLabel = "%d vidéos",
    addToFavorites = "Ajouter aux favoris",
    removeFromFavorites = "Retirer des favoris",
    createPlaylist = "Créer une liste de lecture",
    playlistNamePlaceholder = "Nom de la liste...",
    customPlaylists = "Mes Listes",
    addToPlaylist = "Ajouter à la liste",
    removeFromPlaylist = "Retirer de la liste",
    deleteMediaItem = "Supprimer le fichier",
    deleteMediaConfirmTitle = "Confirmer la suppression",
    deleteMediaConfirmMessage = "Voulez-vous vraiment supprimer définitivement ce fichier ?",
    deletePlaylistConfirmTitle = "Supprimer la liste",
    deletePlaylistConfirmMessage = "Voulez-vous vraiment supprimer cette liste de lecture ?",
    itemAddedToPlaylist = "Ajouté à la liste avec succès",
    itemRemovedFromPlaylist = "Retiré de la liste de lecture",
    itemDeleted = "Fichier supprimé avec succès",
    noCustomPlaylists = "Aucune liste personnalisée. Cliquez sur Créer pour en créer une !",
    trackActionTitle = "Options du média",
    emptyPlaylist = "Cette liste est actuellement vide",
    selectPlaylistToAdd = "Sélectionner une liste",
    newPlaylistTitle = "Nouvelle liste",
    confirmDelete = "Confirmer la suppression",
    bulkDeleteConfirmMessage = "Êtes-vous sûr de vouloir supprimer les éléments sélectionnés ?",
    noPlaylistsFound = "Aucune liste trouvée",
    storageDrives = "Supports & USB",
    backToStorageDrives = "Retour aux supports",
    tabletInternalStorage = "Stockage interne tablette",
    sdCardStorage = "Carte mémoire SD",
    usbDriveLabel = "Clé USB",
    allStorageSources = "Tous les supports",
    aboutSectionTitle = "À propos de l'application",
    appDeveloperLabel = "Développeur",
    developerName = "achour tech pro",
    appVersionLabel = "Version",
    appVersionValue = "v2.5 (Car Head Unit Edition)",
    appFeaturesSummary = "Lecteur multimédia automobile optimisé pour écrans de voiture Android, commandes tactiles géantes, boutons au volant et visualiseur audio dynamique.",
    autoOpenOnUsbTitle = "Ouverture automatique à l'insertion USB",
    autoOpenOnUsbSubtitle = "Lancer ou afficher l'application directement à la connexion d'une clé USB",
    autoOpenOnUsbBadge = "Lancement auto",
    visualizerModeCover = "Pochette d'album",
    visualizerModeBars = "Spectre audio (Barres)",
    toggleVisualizerTooltip = "Basculer entre pochette et barres d'égaliseur",
    screenSizeTitle = "Taille d'écran & Échelle UI",
    screenSizeSubtitle = "Ajuster l'échelle des éléments pour s'adapter parfaitement à l'écran de la voiture",
    fontSizeTitle = "Taille de police",
    fontSizeSubtitle = "Agrandir ou réduire la taille du texte dans toute l'application",
    swcCustomSectionTitle = "Profil de boutons SWC personnalisé",
    swcCustomSectionSubtitle = "Configurer la pause à deux boutons, l'accélération d'appui long et enregistrer comme personnalisé",
    swcCustomBtn1Label = "Code touche volant 1",
    swcCustomBtn2Label = "Code touche volant 2",
    swcCustomAccelLabel = "Facteur d'accélération d'appui long",
    saveCustomProfileBtn = "Enregistrer comme personnalisé",

    // Dashboard Widgets
    widgetsSectionTitle = "Widgets de Bord",
    widgetsSectionSubtitle = "Configurer les informations affichées en plein écran",
    showClock = "Afficher l'horloge",
    showDate = "Afficher la date",
    showTemp = "Afficher la température",
    showSpeed = "Afficher la vitesse",
    speedUnit = "km/h",
    tempUnit = "°C",
    canBusSectionTitle = "Intégration CAN-Bus",
    canBusSectionSubtitle = "Paramètres avancés pour la communication directe avec le véhicule",
    canBusKeyRemapTitle = "Remappage des touches CAN-Bus",
    canBusWheelSwitchTitle = "Commutateur de mode volant",
    canBusWheelSwitchSubtitle = "Changer l'interprétation des signaux de rotation CAN-Bus",
    canBusProtocolTitle = "Protocole CAN",
    canBusCarStatusTitle = "Infos Véhicule",
    canBusVoltage = "Tension Batterie",
    canBusFuel = "Niveau Carburant",
    canBusDoors = "État des Portes",
    canBusCleanUpSwc = "Nettoyer les paramètres inactifs",
    canBusSection = "Paramètres CAN-Bus",
    carSpeedLabel = "Vitesse voiture",
    carTempLabel = "Temp. Ambiante",
    canBusWheelModeLabel = "Mode volant",
    canBusWheelModeNormal = "Normal",
    canBusWheelModeReversed = "Inversé",
    canBusWheelModeSmart = "Intelligent",
    canBusProtocolLabel = "Protocole CAN",
    canBusProtocolGeneric = "Générique (Android)",
    peugeotModeBadge = "Mode Dédié Peugeot 207 / PSA",
    peugeotModeHelp = "Optimisé pour la molette du commodo Peugeot 207, bouton Source et boîtiers Raise/SimpleSoft"
)

class LocalizationManager(context: Context) {
    private val prefs: SharedPreferences = context.getSharedPreferences("car_media_lang_prefs", Context.MODE_PRIVATE)

    companion object {
        private const val KEY_USER_LANGUAGE = "key_user_selected_language"

        /**
         * Strict Rule:
         * If device system language is Arabic -> Arabic
         * If device system language is French -> French
         * If device system language is anything else -> STRICTLY English
         */
        fun getSystemDefaultLanguage(): AppLanguage {
            val systemLang = Locale.getDefault().language.lowercase()
            return when {
                systemLang.startsWith("ar") -> AppLanguage.ARABIC
                systemLang.startsWith("fr") -> AppLanguage.FRENCH
                else -> AppLanguage.ENGLISH
            }
        }
    }

    private val _currentLanguage = MutableStateFlow(determineInitialLanguage())
    val currentLanguage: StateFlow<AppLanguage> = _currentLanguage.asStateFlow()

    private fun determineInitialLanguage(): AppLanguage {
        val savedCode = prefs.getString(KEY_USER_LANGUAGE, null)
        return if (savedCode != null) {
            AppLanguage.fromCode(savedCode)
        } else {
            getSystemDefaultLanguage()
        }
    }

    fun setLanguage(language: AppLanguage) {
        prefs.edit().putString(KEY_USER_LANGUAGE, language.code).apply()
        _currentLanguage.value = language
    }

    fun resetToSystemDefault() {
        prefs.edit().remove(KEY_USER_LANGUAGE).apply()
        _currentLanguage.value = getSystemDefaultLanguage()
    }

    fun getStrings(language: AppLanguage = _currentLanguage.value): AppStrings {
        return when (language) {
            AppLanguage.ARABIC -> ArabicStrings
            AppLanguage.FRENCH -> FrenchStrings
            AppLanguage.ENGLISH -> EnglishStrings
        }
    }
}

val LocalAppStrings = compositionLocalOf { EnglishStrings }
